# Site settings
title: Chalmers Sångkör dokumentation
email: choir@chs.chalmers.se
description: > # this means to ignore newlines until "baseurl:"
  Dokumentation för Chalmers Sångkörs hemsida och tillhörande system.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chalmers-choir.github.io" # the base hostname & protocol for your site

# Standardkategorier i den ordning de skall visas i menyn.
sections: [
  ['auditions', 'Auditions'],
  ['language', 'Språk']
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

permalink: none

# Build settings
markdown: kramdown
